name: ci-auto-release-generic

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: Pre-Release
    runs-on: {{ cookiecutter.ci_runner }}
    permissions:
          contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete latest tag
        id: del-latest-tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: latest
          delete_release: true
        env:
          GITHUB_TOKEN: {{ '${{ secrets.GITHUB_TOKEN }}' }}

      - name: Do Pre-Release
        id: do-pre-release
        uses: softprops/action-gh-release@v1
        with:
          token: {{ '${{ secrets.GITHUB_TOKEN }}' }}
          tag_name: latest
          prerelease: true
          name: Pre-release (dev build)
          # body_path: {{ '${{ github.workspace }}' }}/CHANGES.md
