name: Python-CI-setup

inputs:
  python_version:
    description: The target python version which use to configure the project.
    required: true

runs:
  using: composite
  steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install virtualenv
        run: |
          python -m pip install virtualenv
        shell: bash

      - name: Configure virtualenv
        run: |
          python -m virtualenv .venv
          source .venv/bin/activate
        shell: bash

      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: bash
