name: ci-tests-cpp

env:
  ##############################################################################
  # Please fill in:
  # (Ref. https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables)
  ##############################################################################
  # Target name to compile (test target). Replace the variable accordingly
  ##############################################################################
  TEST_TARGET_NAME: test_target_name
  ##############################################################################
  # Docker image used to generate a container in which to execute this action
  ##############################################################################
  TARGET_DOCKER_IMAGE: ubuntu:jammy
  ##############################################################################
  ##############################################################################
  # Build type for the test run. Defaults to Debug.
  ##############################################################################
  BUILD_TYPE: Debug
  ##############################################################################

on:
  pull_request:
    branches:
      - master

  ##############################################################################
  # Relevant where using it as a reusable workflow
  ##############################################################################
  workflow_call:

jobs:

  run_unit_tests:

    name: Unit Tests
    runs-on: {{ cookiecutter.ci_runner }}

    container:
      image: {{ '${{ env.TARGET_DOCKER_IMAGE }}' }}

      ##########################################################################
      # Please uncomment and fill the following if the image comes from a private repository
      # More info in: https://docs.github.com/en/actions/security-guides/encrypted-secrets
      ##########################################################################
      # credentials:
      #     username: {{ '${{ secrets.RepositoryUser }}' }}
      #     password: {{ '${{ secrets.RepositoryPass }}' }}
      ##########################################################################

    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
          contents: read
          issues: read
          checks: write
          pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Build tests
        id: tests-build
        working-directory: .
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE={{ '${{BUILD_TYPE}}' }}
          cmake --build build -t {{ '${{ env.TEST_TARGET_NAME }}' }}

      - name: Run tests
        id: tests-run
        working-directory: .
        run: |
          ./build/test/{{ '${{ env.TEST_TARGET_NAME }}' }} --reporter junit -o junit/ci-result-junit.xml

      - name: Publish Unit Test Results
        id: tests-publish
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit/ci-result-junit.xml
          action_fail: true
          action_fail_on_inconclusive: true
