name: ci-auto-release-cpp

env:
  ##############################################################################
  # Please fill in:
  # (Ref. https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables)
  ##############################################################################
  # Build type for the release. Defaults to Release.
  ##############################################################################
  BUILD_TYPE: Release
  ##############################################################################

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/ci-tests-cpp.yml

    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

  release:

    name: Release
    runs-on: {{ cookiecutter.ci_runner }}
    needs: [run-tests]

    container:
      ##########################################################################
      # Docker image used to generate a container in which to execute this
      ##########################################################################
      image: ubuntu:jammy

      ##########################################################################
      # Please uncomment and fill the following if the image comes from a private repository
      # More info in: https://docs.github.com/en/actions/security-guides/encrypted-secrets
      ##########################################################################
      # credentials:
      #     username: {{ '${{ secrets.RepositoryUser }}' }}
      #     password: {{ '${{ secrets.RepositoryPass }}' }}
      ##########################################################################

    permissions:
      contents: write # For tags

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build target for Release
        id: release-build
        working-directory: .
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE={{ '${{BUILD_TYPE}}' }}
          cmake --build build

      - name: Package application
        id: release-package
        working-directory: .
        run: |
          cd build
          cpack

      - name: Release tagged
        id: do-tagged-rel
        uses: softprops/action-gh-release@v1
        with:
          token: {{ '${{ secrets.GITHUB_TOKEN }}' }}
          generate_release_notes: true
          # body_path: {{ '${{ github.workspace }}' }}/CHANGES.md
          files: |
            {{ '${{ github.workspace }}' }}/build/packages/*.tar.gz
            {{ '${{ github.workspace }}' }}/build/packages/*.deb
