name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What are the affected version(s) of the OS(s)?
    validations:
      required: false

  - type: textarea
    id: code-sample
    attributes:
      label: Code to produce this issue.
      description: Please copy and paste any relevant code to re-produce this issue.
      render: YAML
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant application logs
      description: Add relevant log excerpt for the application, if applicable.
    validations:
      required: false
