name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Detailed information, fill it where possible / applicable
        ___
        <details>
        <summary>Click me</summary>

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant application logs
      description: Add relevant log excerpt for the application, if applicable.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        </details>

        ### OS / environment information, fill it where possible / applicable
        ___

  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What are the affected version(s) of the OS(s)?
    validations:
      required: false

  - type: input
    id: code-version
    attributes:
      label: Version
      description: What version of the software are you running?
    validations:
      required: true
