name: Feature
description: Add an issue for a new feature / idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please be sure to include as much details & any resources if possible!
  - type: textarea
    id: Suggestion
    attributes:
      label: Suggestion / Feature Request
      description: Describe the feature(s) to be added.
      placeholder: Tell us your suggestion
    validations:
      required: true
