name: Python-CI-setup
description: Setups CI for python workflows

inputs:
  python_version:
    description: The target python version which use to configure the project.
    required: true

runs:
  # Ref. https://joaodlf.com/using-poetry-in-github-actions-the-easy-way.html
  using: composite
  steps:
      - name: Setup Python
        id: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: {{ '${{ inputs.python_version }}' }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache the virtualenv
        id: venv-cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: {{ '${{ runner.os }}' }}-venv-{{ '${{ hashFiles(\'**/poetry.lock\') }}' }}

      - name: Install dependencies
        id: deps-install
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          poetry install
        shell: bash
