name: ci-auto-release-python

on:
  push:
    branches:
      - master

env:
  ##############################################################################
  # Please fill in:
  # Ref. https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables
  ##############################################################################
  # Target python version intended to use to run tests into. Defaults to 3.10.2
  ##############################################################################
  TARGET_PYTHON_VERSION: 3.10.2
  ##############################################################################
  ##############################################################################
  # Target folder where tests reside. Defaults to "tests"
  ##############################################################################
  TESTS_DIRECTORY: tests
  ##############################################################################

jobs:

  pre-release:

    name: Pre-Release
    runs-on: {{ cookiecutter.ci_runner }}

    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
      contents: write # For tags
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup (composite)
        uses: ./.github/actions/ci-setup-python
        with:
          python_version: {{ '${{ env.TARGET_PYTHON_VERSION }}' }}

      - name: Run tests
        run: |
          poetry run python -m pytest {{ '${{ env.TESTS_DIRECTORY }}' }} --doctest-modules --junit-xml=junit/ci-result-junit.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success()
        with:
          files: junit/ci-result-junit.xml
          action_fail: true
          action_fail_on_inconclusive: true

      - name: Package application
        run: |
          rm -rf dist
          poetry build

      - name: Delete latest tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: latest
          delete_release: true
        env:
          GITHUB_TOKEN: {{ '${{ secrets.GITHUB_TOKEN }}' }}

      - name: do-Prerelease
        uses: softprops/action-gh-release@v1
        with:
          token: {{ '${{ secrets.GITHUB_TOKEN }}' }}
          tag_name: latest
          prerelease: true
          name: Pre-release (dev build)
          generate_release_notes: true
          # body_path: {{ '${{ github.workspace }}' }}/CHANGES.md
          files: |
            {{ '${{ github.workspace }}' }}/dist/*
