name: ci-tagged-release-python

env:
  ##############################################################################
  # Please fill in:
  # Ref. https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables
  ##############################################################################
  # Target python version intended to use to run tests into. Defaults to 3.10.2
  ##############################################################################
  TARGET_PYTHON_VERSION: 3.10.2
  ##############################################################################
  ##############################################################################
  # Target folder where tests reside. Defaults to "tests"
  ##############################################################################
  TESTS_DIRECTORY: tests
  ##############################################################################

on:
  push:
    tags:
      - "*.*.*"

jobs:

  run-tests:
    name: Tagged Release Unit Testing
    uses: ./.github/workflows/ci-tests-python.yml

    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

  release:

    name: Tagged-Release
    runs-on: {{ cookiecutter.ci_runner }}
    needs: [run-tests]

    permissions:
      contents: write # For tags

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup (composite)
        id: release-setup
        uses: ./.github/actions/ci-setup-python
        with:
          python_version: {{ '${{ env.TARGET_PYTHON_VERSION }}' }}

      - name: Package application
        id: release-package
        working-directory: .
        run: |
          rm -rf dist
          poetry build

      - name: Release tagged
        id: do-tagged-rel
        uses: softprops/action-gh-release@v1
        with:
          token: {{ '${{ secrets.GITHUB_TOKEN }}' }}
          generate_release_notes: true
          # body_path: {{ '${{ github.workspace }}' }}/CHANGES.md
          files: |
            {{ '${{ github.workspace }}' }}/dist/*
