name: ci-tests-python

env:
  ##############################################################################
  # Please fill in:
  # Ref. https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables
  ##############################################################################
  # Target python version intended to use to run tests into. Defaults to 3.10.2
  ##############################################################################
  TARGET_PYTHON_VERSION:  3.10.2
  ##############################################################################
  ##############################################################################
  # Target folder where tests reside. Defaults to "tests"
  ##############################################################################
  TESTS_DIRECTORY: tests
  ##############################################################################

on:
  pull_request:
    branches:
      - master

  ##############################################################################
  # Relevant where using it as a reusable workflow
  ##############################################################################
  workflow_call:

jobs:
  run_unit_tests:

    name: Unit Tests
    runs-on: {{ cookiecutter.ci_runner }}

    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
          contents: read
          issues: read
          checks: write
          pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup (composite)
        id: tests-setup
        uses: ./.github/workflows/ci-setup-python.yml
        with:
          python_version: {{ '${{ env.TARGET_PYTHON_VERSION }}' }}

      - name: Run tests
        id: tests-run
        working-directory: .
        run: |
          poetry run python -m pytest {{ '${{ env.TESTS_DIRECTORY }}' }} --doctest-modules --junit-xml=junit/ci-result-junit.xml

      - name: Publish Unit Test Results
        id: tests-publish
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit/ci-result-junit.xml
          action_fail: true
          action_fail_on_inconclusive: true
