name: ci-dev-release-auto

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    permissions:
          contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete latest tag
        uses: cb80/delrel@latest
        with:
          tag: latest

      - name: Release development version
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: latest
          prerelease: true
          name: Pre-release (dev build)
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/CHANGELOG.md
