name: ci-auto-release

env:
  TARGET_PYTHON_VERSION: 3.10.2
  TESTS_DIRECTORY: tests

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/ci-tests.yml

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write


  pre-release:
    name: Pre-Release
    runs-on: ubuntu-20.04
    needs: [run-tests]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup (composite)
        id: release-setup
        uses: ./.github/actions/ci-setup-python
        with:
          python_version: ${{ env.TARGET_PYTHON_VERSION }}

      - name: Delete latest tag
        id: del-prev-rel
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: latest
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-Release
        id: do-pre-release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: latest
          prerelease: true
          name: Pre-release (dev build)
          generate_release_notes: true
          body_path: ${{ github.workspace }}/CHANGES.md
