name: ci-tagged-release

env:
  TARGET_PYTHON_VERSION: 3.10.2
  TESTS_DIRECTORY: tests

on:
  push:
    tags:
      - "*.*.*"

jobs:

  run-tests:
    name: Run Unit Tests
    uses: ./.github/workflows/ci-tests-python.yml
    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write


  tagged-release:
    name: Tagged-Release
    runs-on: ubuntu-20.04
    needs: [run-tests]

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup (composite)
        uses: ./.github/actions/ci-setup-python
        with:
          python_version: ${{ env.TARGET_PYTHON_VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          body_path: ${{ github.workspace }}/CHANGES.md
