name: ci-tests-python

env:
  ##############################################################################
  # Please fill in:
  # Ref. https://docs.github.com/en/github-ae@latest/actions/learn-github-actions/variables
  ##############################################################################
  # Target python version intended to use to run tests into. Defaults to 3.10.2
  ##############################################################################
  TARGET_PYTHON_VERSION:  ${{ github.event.inputs.target-python-version || '3.10.2' }}
  ##############################################################################
  ##############################################################################
  # Target folder where tests reside. Defaults to "tests"
  ##############################################################################
  TESTS_DIRECTORY: ${{ github.event.inputs.tests-directory || 'tests' }}
  ##############################################################################

  ##############################################################################
  # Relevant where using it as a reusable workflow
  ##############################################################################
on:
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      target-python-version:
          type: string
          required: true
          description: Target python version
      tests-directory:
          type: string
          required: true
          description: Target directory where to look for tests

jobs:
  # Ref. https://joaodlf.com/using-poetry-in-github-actions-the-easy-way.html
  run_unit_tests:

    runs-on: ubuntu-20.04

    ############################################################################
    # Minimum permissions required by EnricoMi/publish-unit-test-result-action@v2
    # Ref. https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
    ############################################################################
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v3

      - name: Setup (composite)
        uses: ./.github/actions/ci-setup-python
        with:
          python_version: ${{ env.TARGET_PYTHON_VERSION }}

      - name: Run tests
        run: |
          python -m pytest ${{ env.TESTS_DIRECTORY }} --doctest-modules --junit-xml=junit/ci-result-junit.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit/ci-result-junit.xml
          action_fail: true
          action_fail_on_inconclusive: true
